// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';
import * as path from 'path';
import WebviewPanelProvider from './WebviewPanelProvider'
import { startLocalBridgeServer } from './localBridgeServer';
import { PreviewPanelManager } from './previewPanel';
import LayoutEditorProvider, { LAYOUT_EDITOR_VIEW_TYPE } from './layoutEditorProvider';
import { emptyLayoutDocument, parseLayoutDocumentText } from './layoutTypes';
import { generateScaffold, isForeignExistingHtml, scaffoldPathsFor, type VendorAssets } from './scaffoldGen';

const MCP_SERVER_NAME = 'ros2-interfaces';
const DISMISSED_KEY = 'ros2Mcp.setupDismissed';
const WORKSPACE_ENV_VAR = 'ROS2_WEBVIEW_WORKSPACE';
const ROSBRIDGE_URL_ENV_VAR = 'ROS2_WEBVIEW_ROSBRIDGE_URL';

type McpJson = { mcpServers?: Record<string, { command: string; args: string[]; env?: Record<string, string> }> };

function getRosbridgeUrl(): string {
  return vscode.workspace.getConfiguration('ros2Webview').get<string>('rosbridgeUrl', 'ws://localhost:9090');
}

// Key for the bridge port registry file (see bridgeRegistry.ts) — must match
// between the extension host (writer) and the MCP server process (reader).
function getWorkspaceKey(): string {
  return vscode.workspace.workspaceFolders?.[0]?.uri.fsPath ?? 'no-workspace';
}

function resolveWorkspacePath(filePath: string): vscode.Uri {
  if (path.isAbsolute(filePath)) { return vscode.Uri.file(filePath); }
  const folder = vscode.workspace.workspaceFolders?.[0];
  if (!folder) { throw new Error('No workspace folder open to resolve a relative path against.'); }
  return vscode.Uri.joinPath(folder.uri, filePath);
}

type ScaffoldRunResult =
  | { status: 'ok'; htmlUri: vscode.Uri; message: string }
  | { status: 'cancelled' };

// Shared by the "generateGuiScaffold" command (a human clicking a button, where a blocking
// modal overwrite-confirmation is fine) and the MCP tool path below (an agent's HTTP call
// awaiting a response, where a modal that nobody notices would hang indefinitely) — the two
// differ only in `allowPrompt`: false skips the modal and throws a descriptive error instead,
// telling the caller to run the command manually in VS Code to confirm the overwrite.
async function runGenerateScaffold(
  layoutUri: vscode.Uri, opts: { allowPrompt: boolean }, vendorAssets: VendorAssets,
): Promise<ScaffoldRunResult> {
  const { htmlUri } = scaffoldPathsFor(layoutUri);
  if (await isForeignExistingHtml(htmlUri)) {
    if (!opts.allowPrompt) {
      throw new Error(
        `${path.basename(htmlUri.fsPath)} already exists and wasn't generated by this tool. Run ` +
        '"ROS2 Webview: Generate GUI Scaffold" from the Command Palette in VS Code to confirm overwriting it.',
      );
    }
    const choice = await vscode.window.showWarningMessage(
      `${path.basename(htmlUri.fsPath)} already exists and wasn't generated by this command. Overwrite it?`,
      { modal: true }, 'Overwrite',
    );
    if (choice !== 'Overwrite') { return { status: 'cancelled' }; }
  }

  const bytes = await vscode.workspace.fs.readFile(layoutUri);
  const doc = parseLayoutDocumentText(Buffer.from(bytes).toString('utf8'));
  const result = await generateScaffold(doc, layoutUri, getRosbridgeUrl(), vendorAssets);

  const parts = [`Generated ${result.createdPanelIds.length} new panel stub(s); refreshed geometry for all ${doc.panels.length} panel(s).`];
  if (result.orphanedPanelDirs.length) {
    parts.push(`Note: ${result.orphanedPanelDirs.length} panel folder(s) no longer referenced by the layout were left on disk: ${result.orphanedPanelDirs.join(', ')}.`);
  }
  return { status: 'ok', htmlUri: result.htmlUri, message: parts.join(' ') };
}

// A focused .ros2ui.json tab is a custom-editor webview (LayoutEditorProvider), not a
// TextEditor, so `vscode.window.activeTextEditor` (used by previewGeneratedUi below) can't
// find it — the active tab's input has to be read from the tab groups API instead.
function activeRos2uiJsonUri(): vscode.Uri | undefined {
  const input = vscode.window.tabGroups.activeTabGroup.activeTab?.input;
  const uri = input instanceof vscode.TabInputCustom || input instanceof vscode.TabInputText ? input.uri : undefined;
  return uri && /\.ros2ui\.json$/i.test(uri.fsPath) ? uri : undefined;
}

async function readMcpJson(uri: vscode.Uri): Promise<McpJson> {
  try {
    const bytes = await vscode.workspace.fs.readFile(uri);
    return JSON.parse(Buffer.from(bytes).toString('utf8')) as McpJson;
  } catch {
    return {};
  }
}

function serverEntry(context: vscode.ExtensionContext) {
  return {
    command: process.execPath,
    args: [path.join(context.extensionUri.fsPath, 'dist', 'mcpServer.js')],
    env: {
      [WORKSPACE_ENV_VAR]: getWorkspaceKey(),
      [ROSBRIDGE_URL_ENV_VAR]: getRosbridgeUrl(),
    },
  };
}

type ClaudeSettingsJson = {
  enabledMcpjsonServers?: string[];
  permissions?: { allow?: string[] } & Record<string, unknown>;
} & Record<string, unknown>;

// Claude Code gates a project MCP server behind two separate approvals: first
// whether to trust the server declared in .mcp.json at all (enabledMcpjsonServers),
// then — once trusted — whether to approve each individual tool call
// (permissions.allow). Both have to be granted, or the user still gets
// prompted at the first gate even though the second is wide open. "Set Up"
// grants both up front rather than leaving the user to discover either by hand.
//
// Written to settings.local.json rather than settings.json: Claude Code
// requires the user to click through a one-time "trust this folder" prompt
// before it honors *project*-tier settings (committed, potentially authored
// by someone else) — but settings.local.json is a different tier, always
// treated as the user's own, so these grants take effect immediately with
// no extra prompt.
async function grantClaudeCodeMcpPermission(folder: vscode.WorkspaceFolder): Promise<void> {
  const settingsUri = vscode.Uri.joinPath(folder.uri, '.claude', 'settings.local.json');
  const permissionRule = `mcp__${MCP_SERVER_NAME}__*`;

  let settings: ClaudeSettingsJson = {};
  try {
    const bytes = await vscode.workspace.fs.readFile(settingsUri);
    settings = JSON.parse(Buffer.from(bytes).toString('utf8')) as ClaudeSettingsJson;
  } catch {
    // No existing file (or unreadable) — start fresh rather than fail setup.
  }

  const enabledServers = (settings.enabledMcpjsonServers ??= []);
  if (!enabledServers.includes(MCP_SERVER_NAME)) {
    enabledServers.push(MCP_SERVER_NAME);
  }

  settings.permissions ??= {};
  const allow = (settings.permissions.allow ??= []);
  if (!allow.includes(permissionRule)) {
    allow.push(permissionRule);
  }

  await vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(folder.uri, '.claude'));
  await vscode.workspace.fs.writeFile(settingsUri, Buffer.from(JSON.stringify(settings, null, 2) + '\n', 'utf8'));
}

async function readExtensionFile(context: vscode.ExtensionContext, ...segments: string[]): Promise<string> {
  const bytes = await vscode.workspace.fs.readFile(vscode.Uri.joinPath(context.extensionUri, ...segments));
  return Buffer.from(bytes).toString('utf8');
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const CLAUDE_MD_BLOCK_START = '<!-- ros2-webview-extension: managed block, edits here are overwritten by "Set Up" -->';
const CLAUDE_MD_BLOCK_END = '<!-- /ros2-webview-extension -->';

// CLAUDE.md is project-scoped — Claude Code only reads it from whatever workspace it's
// pointed at, so bundling it with the extension does nothing for a user's own ROS2 project
// until it's copied there. "Set Up" does that, the same way it already does for .mcp.json
// and settings.local.json above.
//
// The MCP server's own `instructions` field (see mcpServer.ts) carries a condensed version
// of this same guidance unconditionally, over the protocol itself, regardless of whether the
// user ever runs "Set Up" — this file-based copy is the fuller version for those who do.
async function installClaudeMdSection(folder: vscode.WorkspaceFolder, context: vscode.ExtensionContext): Promise<void> {
  const claudeMdUri = vscode.Uri.joinPath(folder.uri, 'CLAUDE.md');
  const sectionBody = (await readExtensionFile(context, 'CLAUDE.md')).trim();
  const block = `${CLAUDE_MD_BLOCK_START}\n${sectionBody}\n${CLAUDE_MD_BLOCK_END}`;

  let existing = '';
  try {
    const bytes = await vscode.workspace.fs.readFile(claudeMdUri);
    existing = Buffer.from(bytes).toString('utf8');
  } catch {
    // No existing file — the block becomes the entire content.
  }

  const blockRe = new RegExp(`${escapeRegExp(CLAUDE_MD_BLOCK_START)}[\\s\\S]*?${escapeRegExp(CLAUDE_MD_BLOCK_END)}`);
  const next = blockRe.test(existing)
    ? existing.replace(blockRe, block)
    : existing
      ? `${existing.trimEnd()}\n\n${block}\n`
      : `${block}\n`;

  await vscode.workspace.fs.writeFile(claudeMdUri, Buffer.from(next, 'utf8'));
}

// Vendored from https://github.com/ConardLi/web-design-skill (skills/web-design-engineer) so
// Claude has real design-system guidance (design tokens, anti-AI-cliché rules, style recipes)
// available when a user asks for visual polish on a generated GUI, not just the narrow
// per-panel defaults baked into scaffoldGen.ts. Copied wholesale (vscode.workspace.fs.copy
// handles the directory recursively) and always overwritten on Set Up, same as CLAUDE.md's
// managed block — it's third-party vendored content, not something a user hand-edits in place.
async function installDesignSkill(folder: vscode.WorkspaceFolder, context: vscode.ExtensionContext): Promise<void> {
  const sourceUri = vscode.Uri.joinPath(context.extensionUri, '.claude', 'skills', 'web-design-engineer');
  const targetUri = vscode.Uri.joinPath(folder.uri, '.claude', 'skills', 'web-design-engineer');
  await vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(folder.uri, '.claude', 'skills'));
  await vscode.workspace.fs.copy(sourceUri, targetUri, { overwrite: true });
}

async function setupClaudeCodeMcp(context: vscode.ExtensionContext): Promise<void> {
  const folder = vscode.workspace.workspaceFolders?.[0];
  if (!folder) {
    vscode.window.showErrorMessage('Open a folder/workspace first to set up the ROS2 MCP server.');
    return;
  }

  const mcpJsonUri = vscode.Uri.joinPath(folder.uri, '.mcp.json');
  const config = await readMcpJson(mcpJsonUri);
  config.mcpServers ??= {};
  config.mcpServers[MCP_SERVER_NAME] = serverEntry(context);

  await vscode.workspace.fs.writeFile(mcpJsonUri, Buffer.from(JSON.stringify(config, null, 2) + '\n', 'utf8'));
  await grantClaudeCodeMcpPermission(folder);
  await installClaudeMdSection(folder, context);
  await installDesignSkill(folder, context);
  vscode.window.showInformationMessage(
    'ROS2 MCP server registered in .mcp.json (tool calls pre-approved) with CLAUDE.md guidance and the ' +
    'web-design-engineer skill installed. Restart Claude Code (or run /mcp) to pick it up.',
  );
}

async function maybeOfferMcpSetup(context: vscode.ExtensionContext): Promise<void> {
  const folder = vscode.workspace.workspaceFolders?.[0];
  if (!folder || context.globalState.get<boolean>(DISMISSED_KEY)) { return; }

  const config = await readMcpJson(vscode.Uri.joinPath(folder.uri, '.mcp.json'));
  if (config.mcpServers?.[MCP_SERVER_NAME]) { return; }

  const choice = await vscode.window.showInformationMessage(
    'Let Claude Code read ROS2 msg/srv/action schemas in this workspace via MCP?',
    'Set Up', "Don't Ask Again",
  );
  if (choice === 'Set Up') {
    await setupClaudeCodeMcp(context);
  } else if (choice === "Don't Ask Again") {
    await context.globalState.update(DISMISSED_KEY, true);
  }
}

// This method is called when your extension is activated
// Your extension is activated the very first time the command is executed
// Read once at activation and threaded everywhere generateScaffold() is called — see
// VendorAssets' doc comment in scaffoldGen.ts for why these get copied into the user's own
// workspace instead of being loaded from the extension install dir at preview time.
const VENDOR_ASSET_PATHS = [
  'tailwind.min.css',
  'tailwind-build/README.md',
  'tailwind-build/tailwind.config.js',
  'tailwind-build/input.css',
  'design-tokens.css',
];

async function loadVendorAssets(context: vscode.ExtensionContext): Promise<VendorAssets> {
  const entries = await Promise.all(
    VENDOR_ASSET_PATHS.map(async relPath => [relPath, await readExtensionFile(context, 'media', 'vendor', relPath)] as const),
  );
  return Object.fromEntries(entries);
}

export async function activate(context: vscode.ExtensionContext) {

  const provider = new WebviewPanelProvider(context.extensionUri);
  provider.registEvent(provider.createOperationEventCallback());

  context.subscriptions.push(
    vscode.window.registerWebviewViewProvider(WebviewPanelProvider.viewType, provider,
      {webviewOptions: {
        retainContextWhenHidden: true
      }})
  );

  const vendorAssets = await loadVendorAssets(context);
  const previewManager = new PreviewPanelManager(getRosbridgeUrl, vendorAssets);

  context.subscriptions.push(
    vscode.window.registerCustomEditorProvider(
      LAYOUT_EDITOR_VIEW_TYPE,
      new LayoutEditorProvider(context.extensionUri),
      { webviewOptions: { retainContextWhenHidden: true } },
    )
  );

  const bridgeServer = startLocalBridgeServer(
    {
      openPreview: async (filePath) => previewManager.open(resolveWorkspacePath(filePath)),
      generateGuiScaffold: async (filePath) => {
        const result = await runGenerateScaffold(resolveWorkspacePath(filePath), { allowPrompt: false }, vendorAssets);
        // allowPrompt: false never returns 'cancelled' (it throws instead) — this satisfies the type.
        if (result.status === 'cancelled') { throw new Error('Cancelled.'); }
        await previewManager.open(result.htmlUri);
        return { htmlPath: result.htmlUri.fsPath, message: result.message };
      },
    },
    getWorkspaceKey(),
  );
  context.subscriptions.push({ dispose: () => bridgeServer.dispose() });

  context.subscriptions.push(
    vscode.lm.registerMcpServerDefinitionProvider('ros2-webview-extension.mcpServers', {
      provideMcpServerDefinitions: () => {
        const serverPath = path.join(context.extensionUri.fsPath, 'dist', 'mcpServer.js');
        const definition = new vscode.McpStdioServerDefinition('ROS2 Interfaces', process.execPath, [serverPath]);
        definition.env = {
          [WORKSPACE_ENV_VAR]: getWorkspaceKey(),
          [ROSBRIDGE_URL_ENV_VAR]: getRosbridgeUrl(),
        };
        return [definition];
      },
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('ros2-webview-extension.setupClaudeCodeMcp', () => setupClaudeCodeMcp(context))
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('ros2-webview-extension.previewGeneratedUi', async (uri?: vscode.Uri) => {
      const target = uri ?? vscode.window.activeTextEditor?.document.uri;
      if (target && /\.html?$/i.test(target.fsPath)) {
        await previewManager.open(target);
        return;
      }
      const picked = await vscode.window.showOpenDialog({
        canSelectMany: false,
        filters: { 'HTML': ['html', 'htm'] },
        title: 'Select the generated UI to preview',
      });
      if (picked?.[0]) {
        await previewManager.open(picked[0]);
      }
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('ros2-webview-extension.newLayoutFile', async () => {
      const folder = vscode.workspace.workspaceFolders?.[0];
      if (!folder) {
        vscode.window.showErrorMessage('Open a folder/workspace first to create a layout file.');
        return;
      }

      const name = await vscode.window.showInputBox({
        prompt: 'Name for the new layout file',
        value: 'ui-layout',
        validateInput: v => v.trim() ? null : 'Enter a name.',
      });
      if (!name) { return; }

      const fileName = name.endsWith('.ros2ui.json') ? name : `${name}.ros2ui.json`;
      const uri = vscode.Uri.joinPath(folder.uri, fileName);

      try {
        await vscode.workspace.fs.stat(uri);
        vscode.window.showErrorMessage(`${fileName} already exists.`);
        return;
      } catch {
        // Doesn't exist yet — good, create it.
      }

      const content = JSON.stringify(emptyLayoutDocument(), null, 2) + '\n';
      await vscode.workspace.fs.writeFile(uri, Buffer.from(content, 'utf8'));
      await vscode.commands.executeCommand('vscode.openWith', uri, LAYOUT_EDITOR_VIEW_TYPE);
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('ros2-webview-extension.generateGuiScaffold', async (uri?: vscode.Uri) => {
      const target = uri ?? activeRos2uiJsonUri();
      const layoutUri = target ?? (await vscode.window.showOpenDialog({
        canSelectMany: false,
        filters: { 'ROS2 Layout': ['json'] },
        title: 'Select the .ros2ui.json layout file to generate a GUI scaffold from',
      }))?.[0];
      if (!layoutUri) { return; }

      try {
        const result = await runGenerateScaffold(layoutUri, { allowPrompt: true }, vendorAssets);
        if (result.status === 'cancelled') { return; }
        vscode.window.showInformationMessage(result.message);
        await previewManager.open(result.htmlUri);
      } catch (err) {
        vscode.window.showErrorMessage(`Failed to generate GUI scaffold: ${err instanceof Error ? err.message : String(err)}`);
      }
    })
  );

  void maybeOfferMcpSetup(context);

}

// This method is called when your extension is deactivated
export function deactivate() {}
