import * as vscode from 'vscode';
import * as path from 'path';
import { parseLayoutDocumentText } from './layoutTypes';
import { generateScaffold, isForeignExistingHtml, scaffoldPathsFor, type VendorAssets } from './scaffoldGen';
import { getRosbridgeUrl, readExtensionFile } from './workspaceConfig';

// The user-facing entry points around scaffoldGen.ts's pure generator:
// overwrite confirmation, result messaging, and the vendored assets that get
// copied into the user's workspace alongside the generated files.

export type ScaffoldRunResult =
  | { status: 'ok'; htmlUri: vscode.Uri; message: string }
  | { status: 'cancelled' };

// Shared by the "generateGuiScaffold" command (a human clicking a button, where a blocking
// modal overwrite-confirmation is fine) and the MCP tool path (an agent's HTTP call
// awaiting a response, where a modal that nobody notices would hang indefinitely) — the two
// differ only in `allowPrompt`: false skips the modal and throws a descriptive error instead,
// telling the caller to run the command manually in VS Code to confirm the overwrite.
export async function runGenerateScaffold(
  layoutUri: vscode.Uri, opts: { allowPrompt: boolean }, vendorAssets: VendorAssets,
): Promise<ScaffoldRunResult> {
  const { htmlUri } = scaffoldPathsFor(layoutUri);
  if (await isForeignExistingHtml(htmlUri)) {
    if (!opts.allowPrompt) {
      throw new Error(
        `${path.basename(htmlUri.fsPath)} already exists and wasn't generated by this tool. Run ` +
        '"ROS2 Webview: Generate GUI Scaffold" from the Command Palette in VS Code to confirm overwriting it.',
      );
    }
    const choice = await vscode.window.showWarningMessage(
      `${path.basename(htmlUri.fsPath)} already exists and wasn't generated by this command. Overwrite it?`,
      { modal: true }, 'Overwrite',
    );
    if (choice !== 'Overwrite') { return { status: 'cancelled' }; }
  }

  const bytes = await vscode.workspace.fs.readFile(layoutUri);
  const doc = parseLayoutDocumentText(Buffer.from(bytes).toString('utf8'));
  const result = await generateScaffold(doc, layoutUri, getRosbridgeUrl(), vendorAssets);

  const parts = [`Generated ${result.createdPanelIds.length} new panel stub(s); refreshed geometry for all ${doc.panels.length} panel(s).`];
  if (result.orphanedPanelDirs.length) {
    parts.push(`Note: ${result.orphanedPanelDirs.length} panel folder(s) no longer referenced by the layout were left on disk: ${result.orphanedPanelDirs.join(', ')}.`);
  }
  return { status: 'ok', htmlUri: result.htmlUri, message: parts.join(' ') };
}

// Read once at activation and threaded everywhere generateScaffold() is called — see
// VendorAssets' doc comment in scaffoldGen.ts for why these get copied into the user's own
// workspace instead of being loaded from the extension install dir at preview time.
const VENDOR_ASSET_PATHS = [
  'tailwind.min.css',
  'tailwind-build/README.md',
  'tailwind-build/tailwind.config.js',
  'tailwind-build/input.css',
  'design-tokens.css',
];

export async function loadVendorAssets(context: vscode.ExtensionContext): Promise<VendorAssets> {
  const entries = await Promise.all(
    VENDOR_ASSET_PATHS.map(async relPath => [relPath, await readExtensionFile(context, 'media', 'vendor', relPath)] as const),
  );
  return Object.fromEntries(entries);
}
